import React, { useState, useEffect } from "react";
import Stripe from "stripe";
import Head from "next/head";
import Hero from "../components/Hero";
import PurchaseCard from "../components/PurchaseCard";
import { useAppContext } from "../context/CardContext";

export async function getServerSideProps(context) {
	const stripe = new Stripe(process.env.STRIPE_SECRET ?? "", {
		apiVersion: "2020-08-27",
	});

	const res = await stripe.prices.list({
		limit: 10,
		expand: ["data.product"],
	});

	const prices = res.data.filter((price) => price.active);

	return {
		props: { prices },
	};
}

export default function Home({ prices }) {
	const { state, dispatch } = useAppContext();
	const [index, setIndex] = useState(true);

	useEffect(() => {
		dispatch({
			type: "set_prices",
			value: prices,
		});
	}, [prices]);

	return (
		<div>
			<Head>
				<title>Shoe-Commerce</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Hero />

			<div className='flex flex-col space-y-4 md:flex-row md:space-y-2 md:space-x-5 lg:space-x-20'>
				{prices.map((price, index) => {
					return (
						<PurchaseCard key={index} price={price}></PurchaseCard>
					);
				})}
			</div>
		</div>
	);
}
