import React, { useState, useEffect } from "react";
import Stripe from "stripe";
import { useAppContext } from "../context/CardContext";
import PurchaseCard from "../components/PurchaseCard";

export async function getServerSideProps(context) {
	const stripe = new Stripe(process.env.STRIPE_SECRET ?? "", {
		apiVersion: "2020-08-27",
	});

	const res = await stripe.prices.list({
		limit: 10,
		expand: ["data.product"],
	});

	const prices = res.data.filter((price) => price.active);

	return {
		props: { prices },
	};
}

const products = ({ prices }) => {
	const { state, dispatch } = useAppContext();
	const [index, setIndex] = useState(true);
	// const featuredPrices = prices.slice(2, 6);

	useEffect(() => {
		dispatch({
			type: "set_prices",
			value: prices,
		});
	}, [prices]);

	return (
		<div className='border-b-2 border-red-400 pb-10'>
			<title>Shoe-In-Stock</title>
			<meta name='description' content='Generated by create next app' />
			<meta
				content='width=device-width, initial-scale=1'
				name='viewport'
			/>
			<link rel='icon' href='/favicon.ico' />

			<div className='flex justify-center items-center space-x-4 py-14 px-5'>
				<h1 className=' text-lg text-slate-900 font-semibold tracking-wider whitespace-nowrap md:text-2xl lg:text-3xl'>
					Save up to 60% off
				</h1>
				<div>
					<h2 className='text-sm uppercase whitespace-nowrap md:text-lg'>
						Login and use code save60 at checkout
					</h2>
					<div className='bg-slate-900 h-0.5 w-full'></div>
				</div>
			</div>
			<div className='w-11/12 mx-auto grid grid-cols-2 gap-6 md:grid-cols-4 md:gap-8 lg:grid-cols-8 lg:grid-rows-2 '>
				{prices.map((price, index) => {
					return (
						<PurchaseCard key={index} price={price}></PurchaseCard>
					);
				})}
			</div>
		</div>
	);
};

export default products;
